### ISSUE TITLE
Cannot get it to work (cylon-mqtt)

### ISSUE THREAD

**Issue by bartpeperkamp** [hybridgroup/cylon-mqtt#6]
I am unable to get the mqtt module to work. After connecting to my broker it gives me the error 'Cannot read property 'subscribe' of undefined'. I used the sample code and only replaced the broker. Any idea what is going wrong?

**Comment by bartpeperkamp** [comment]
My code is this: 

var Cylon = require('cylon');

Cylon.robot({
  connections: {
    server: { adaptor: 'mqtt', host: 'mqtt://mqtt.thethings.io:1883/v2/things/removedthetoken' }
  },

  work: function(my) {
    my.server.subscribe('hello');

    my.server.on('message', function (topic, data) {
      console.log(topic + ": " + data);
    });

    every((1).seconds(), function() {
      console.log("Saying hello...");
      my.server.publish('hello', 'hi there');
    });
  }
}).start();

**Comment by edgarsilva** [comment]
Will check it out and test, should be an issue with an updated adaptor. Will update here once I fix the issue.

**Comment by bartpeperkamp** [comment]
Thx! I suspect it is a conflict with other modules. Did a clean install in an empty dir and it worked. Must be a conflict with the npm module mqtt.. I'll test it when i get home

**Comment by bartpeperkamp** [comment]
Clean install with just cylon and cylon-mqtt

**Comment by edgarsilva** [comment]
Oh! glad to hear, might be because you were using and older version of the driver/adaptor and cylon core was updated. Could you please close this issue?

**Comment by bartpeperkamp** [comment]
It's closed already :) To summarize: it was a conflict with multiple MQTT node modules. Just using the cylon-mqtt module is probably best...
